### ISSUE TITLE
Cannot read property 'classToast' of undefined

### ISSUE THREAD

**Issue by mfollert** [acidjazz/nuxt-tailvue#1]
`this.$toast.success('Settings has been saved.', {})`

`client.js?06a0:97 TypeError: Cannot read property 'classToast' of undefined
    at VueComponent.classToastAll (tv-toast.vue?273a:169)`

Error in:
`classToastAll () {
      if (this.defaults.classToast) {
        return [this.classToast, this.defaults.classToast]
      }
      return [this.classToast]
    },`

Used module config:
` ['nuxt-tailvue', { toast: true }],`

**Comment by mfollert** [comment]
**Fix:**
In tv-toast.vue in line 153 change `default: () => {},` to `default: () => ({}),`

**Comment by acidjazz** [comment]
@mfollert both packages updated
